### PR TITLE
Updating the Product Owner information in preparation for the 2022 autumn request for maintenance

### PR DESCRIPTION
**Pull request by jrgriffiniii**
This is necessary in order to request from the community renewed efforts for maintenance, and to direct those outside of the community to the Samvera Slack.

### CODE REVIEW

**Review by cjcolvar — COMMENTED** [review]
I plan on continuing being PO for hydra-head.

**Review by bess — CHANGES_REQUESTED** [review]
Looks like @cjcolvar wants to stay on as PO! 🎉

**Comment by jrgriffiniii** [comment]
I apologize for my errors with this @cjcolvar, please find the updated commits ready for review please.

**Review by cjcolvar — APPROVED** [review]
Thanks for cleaning this up!

**Pull request merged**
