### PR TITLE
Adding CONTRIBUTING.md

This was uploaded via automation.

### PR DESCRIPTION
**Pull request by jeremyf**

### CODE REVIEW

**Comment by cjcolvar** [comment]
There is a CONTRIBUTING.md already in the `.github` directory.  Do you think one should be added at the root as well or the files in `.github` moved to the repo root?

**Comment by jeremyf** [comment]
My inclination is that the .github is a weird specific case, and would prefer in ./ of the project.

I do believe we should look at uniformity.  Perhaps something to bring up on Samvera Tech?

**Comment by cjcolvar** [comment]
This was discussed on a [Samvera Tech call](https://wiki.lyrasis.org/display/samvera/Samvera+Tech+Call+2020-07-08) and it was decided that these documents should live in the root of the repository.

**Comment by cjcolvar** [comment]
The Renaming Branch Working Group is in the process of renaming the default branch from master to main in Samvera and Samvera-Labs repos. This brings repositories into compliance with the Samvera Community Code of Conduct (https://samvera.atlassian.net/wiki/spaces/samvera/pages/405212316/Code+of+Conduct) and language recommendations (https://github.com/samvera/maintenance/blob/master/templates/CONTRIBUTING.md#language). Background on the renaming effort is available in the working group notes (https://samvera.atlassian.net/wiki/x/b5IYHg).

I just updated the default branch name for hydra-head which had the side effect of closing your pull request. Please reopen this pull request targeting the main branch if it is still relevant. Thanks!

**Pull request closed without merging**
