### PR TITLE
Revert part of #421

### PR DESCRIPTION
**Pull request by jcoyne**
Because `render nothing:true` is not supported in Rails 5.1

This fixes the failure seen in #426

### CODE REVIEW

**Comment by jrochkind** [comment]
Uh oh, that's too bad.  If you revert this, you are going to revert the fix to get HTTP headers to be sent immediately on these streaming deliveries, and probably go back to the situation where it takes 10+ seconds for headers to be sent, which is bad UI, and times out some automated services (such as caches) that will be fetching. 

I don't know what the solution is, figure out the alternative in rails 5.1 instead of reverting I guess?

**Comment by jrochkind** [comment]
My guess is this might work for Rails 5.1, as well as older Rails, and have been the correct way to do it all along:

    render body: iostream

Replacing the two lines with that one. 

It's also possible it would work if you just removed the `render` line entirely, but left `response.body = iostream`, the trick is you gotta stop rails from trying to render a view here, just using our iostream.

**Comment by jcoyne** [comment]
If you do `render body: iostream` then it calls `#to_s` on iostream, which doesn't seem to be what we want:

```
     Failure/Error: expect(response.body).to eq 'one1two2threfour'

       expected: "one1two2threfour"
            got: "#<ActiveFedora::File::Streaming::FileBody:0x00007feaacc66800>"

       (compared using ==)
```

**Comment by jrochkind** [comment]
That is indeed terrible. Gah. What if you just remove the `render` line entirely, but leave `response.body = iostream`.  Either it'll work, or it'll try to render a view we don't want. 

I find a blog that seems to suggest just removing the `render` will work. I'm thinking maybe the `render` line was actually always a no-op. 

https://coderwall.com/p/kad56a/streaming-large-data-responses-with-rails

**Comment by jcoyne** [comment]
I tried just doing `response.body = iostream` but then it tries to do the default render and it raises an error that it can't find the show template.

**Comment by jrochkind** [comment]
How annoying. There's gotta be a way to do this right. Maybe we gotta file an issue with Rails or something.

**Comment by jrochkind** [comment]
The example on the coderwall blog actually has `self.response_body = stream`, rather than `response.body = stream`.  But looking at method definitions, not sure if that will be any different. This is annoying. Sorry, I don't mean to be trying to get you to code-by-wire to my instruction, I'll try to find some time to mess with it myself.

**Pull request merged**
