### PR TITLE
Updates the CircleCI configuration to test against Ruby releases 2.6.3, 2.5.5, and 2.4.6

### LINKED ISSUE #486: Test against Ruby releases 2.6.3, 2.5.5, and 2.4.6
Derived from samvera/maintenance#17

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Resolves #486

### CODE REVIEW

**Comment by cjcolvar** [comment]
@jrgriffiniii Any idea why coveralls isn't reporting?  I'm fine merging without it but just curious.

**Comment by jrgriffiniii** [comment]
I've updated the CircleCI configuration and retriggered the build, hopefully it should report for this run.

**Comment by cjcolvar** [comment]
Maybe coveralls isn't running because it is a PR from a fork?

**Comment by jrgriffiniii** [comment]
No, that's what I had assumed.  I updated the CircleCI config. for my fork, but not for the main repository - it was missing the COVERALLS_REPO_TOKEN.

**Comment by jrgriffiniii** [comment]
I'm sorry for missing this earlier, https://github.com/samvera/hydra-head/pull/483/files was merged on 03/29/19, but the last report on Coveralls was generated on 03/25: https://coveralls.io/github/samvera/hydra-head.  I'll look into the `coveralls` integration for the Gem.

**Comment by jrgriffiniii** [comment]
Coveralls reporting was restored with https://github.com/samvera/hydra-head/pull/487/commits/fa29a6b6f650d1927e0c6a07d2679bd86074acfb: https://coveralls.io/builds/23314337

**Pull request merged**
